var programs = [
  {
    number: 1,
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Bubble Sort',
    shortDescription: 'Visual representation of the Bubble sort algorithm.',
    imgpath: 'Sorting/1.%20Bubble%20Sort/image.png',
    filepath: 'Sorting/1.%20Bubble%20Sort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Bubble_sort',
    description: 'This is a visual representation of the ',
    algLink:     'Bubble sort algorithm',
    downloadLink: 'Bubble%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 2,
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Count Sort',
    shortDescription: 'Visual representation of the Count sort algorithm.',
    imgpath: 'Sorting/2.%20Count%20Sort/image.png',
    filepath: 'Sorting/2.%20Count%20Sort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Counting_sort',
    description: 'This is a visual representation of the ',
    algLink:     'Count sort algorithm',
    downloadLink: 'Count%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 3,
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Gnome Sort',
    shortDescription: 'Visual representation of the Gnome sort algorithm.',
    imgpath: 'Sorting/3.%20Gnome%20Sort/image.png',
    filepath: 'Sorting/3.%20Gnome%20Sort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Gnome_sort',
    description: 'This is a visual representation of the ',
    algLink:     'Gnome sort algorithm',
    downloadLink: 'Gnome%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 4,
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Insertion Sort',
    shortDescription: 'Visual representation of the Insertion sort algorithm.',
    imgpath: 'Sorting/4.%20Insertion%20Sort/image.png',
    filepath: 'Sorting/4.%20Insertion%20Sort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Insertion_sort',
    description: 'This is a visual representation of the ',
    algLink:     'Insertion sort algorithm',
    downloadLink: 'Insertion%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 5,
    tags: ['Math', 'JavaScript', 'Visualization'],
    title: 'Babbage Problem',
    shortDescription: 'Solving the Charles Babbage problem',
    imgpath: 'Projects/6.Babbage-Problem/image.png',
    filepath: 'Projects/6.Babbage-Problem/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Babbage_problem',
    description: 'This program solves the ',
    algLink:     'Babbage Problem',
    downloadLink: 'Babbage-Problem.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 6,
    tags: ['Math', 'JavaScript', 'Visualization'],
    title: 'Binary Numbers',
    shortDescription: 'Converting Base 10 to 2',
    imgpath: 'Projects/7.BinaryNumbers/image.png',
    filepath: 'Projects/7.BinaryNumbers/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Binary_digits',
    description: 'Converts base 10 numbers to ',
    algLink:     'binary digits.',
    downloadLink: 'BinaryNumbers.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 7,
    tags: ['Cryptography', 'JavaScript', 'Console'],
    title: 'Caesar Cipher',
    shortDescription: 'Encrypt/Decrypt text using a Caesar Cipher',
    imgpath: 'Projects/8.Caesar-Cipher/image.png',
    filepath: 'Projects/8.Caesar-Cipher/index.html',
    rosettaLink: 'https://www.rosettacode.org/wiki/Caesar_cipher',
    description: 'Encrypt/Decrypt text using a ',
    algLink:     'Caesar Cipher.',
    downloadLink: 'Caesar-Cipher.zip',
    p5: false,
    console: true,
    visible: true
  },
  {
    number: 8,
    tags: ['Cryptography', 'JavaScript', 'Console'],
    title: 'Rot-13 Cipher',
    shortDescription: 'Encrypt/Decrypt text using a Rot-13 Cipher',
    imgpath: 'Projects/9.Rot-13/image.png',
    filepath: 'Projects/9.Rot-13/index.html',
    rosettaLink: 'https://www.rosettacode.org/wiki/Rot-13',
    description: 'Encrypt/Decrypt text using a ',
    algLink:     'Rot-13 Cipher.',
    downloadLink: 'Rot-13.zip',
    p5: false,
    console: true,
    visible: true
  },
  {
    number: 9,
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Starfield',
    shortDescription: 'Fly through space at warpspeed!',
    imgpath: 'CodingChallenges/10.Starfield/image.png',
    filepath: 'CodingChallenges/10.Starfield/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=17WoOqgXsRM',
    description: 'Fly through space at ',
    algLink:     'warpspeed!',
    downloadLink: 'Starfield.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 10,
    tags: ['Challenge', 'JavaScript', 'Game'],
    title: 'Snake',
    shortDescription: 'Play the retro arcade game: Snake',
    imgpath: 'CodingChallenges/11.SnakeGame/image.png',
    filepath: 'CodingChallenges/11.SnakeGame/index.html',
    rosettaLink: 'https://youtu.be/AaGK-fj-BAM',
    description: 'Use the <b>Arrow Keys</b> to play the ',
    algLink:     'Snake Game!',
    downloadLink: 'SnakeGame.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 11,
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Purple Rain',
    shortDescription: 'Play in the Purple Rain!',
    imgpath: 'CodingChallenges/12.PurpleRain/image.png',
    filepath: 'CodingChallenges/12.PurpleRain/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=KkyIDI6rQJI',
    description: 'Watch the ',
    algLink:     'Purple Rain fall!',
    downloadLink: 'PurpleRain.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 12,
    tags: ['Challenge', 'JavaScript', 'Game'],
    title: 'Space Invaders',
    shortDescription: 'Play the classic: Space Invaders',
    imgpath: 'CodingChallenges/13.SpaceInvaders/image.png',
    filepath: 'CodingChallenges/13.SpaceInvaders/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=biN3v3ef-Y0',
    description: 'Use <b>"A"</b> and <b>"D"</b> to move and <b>Spacebar</b> to shoot - ',
    algLink:     'Space Invaders',
    downloadLink: 'SpaceInvaders.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 13,
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Solar System',
    shortDescription: 'Solar System Simulation!',
    imgpath: 'CodingChallenges/14.SolarSystem/image.png',
    filepath: 'CodingChallenges/14.SolarSystem/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=l8SiJ-RmeHU',
    description: 'A Solar System ',
    algLink:     'Simulation!',
    downloadLink: 'SolarSystem.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 14,
    tags: ['Challenge', 'Visualization'],
    title: 'Maze Generator',
    shortDescription: 'Generate a maze using a recursive backtracker!',
    imgpath: 'CodingChallenges/15.MazeGenerator/image.png',
    filepath: 'CodingChallenges/15.MazeGenerator/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/Maze_generation_algorithm#Recursive_backtracker',
    description: 'Generates a maze using a ',
    algLink:     'Recursive backtracker',
    downloadLink: 'MazeGenerator.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 15,
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'RDA!',
    shortDescription: 'Reaction Diffusion Algorithm Simulation',
    imgpath: 'CodingChallenges/16.ReactionDiffusion/image.png',
    filepath: 'CodingChallenges/16.ReactionDiffusion/index.html',
    rosettaLink: 'http://karlsims.com/rd.html',
    description: 'This is a Simulation based on the ',
    algLink:     'Reaction Diffusion Algorithm',
    downloadLink: 'ReactionDiffusionAlg.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 16,
    tags: ['Challenge', 'Visualization'],
    title: 'Fractal Tree - Recursive',
    shortDescription: 'Build a fractal tree recursively.',
    imgpath: 'CodingChallenges/17.FractalTrees/image.png',
    filepath: 'CodingChallenges/17.FractalTrees/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=0jjeOYMjmDU',
    description: 'Animated Recursive',
    algLink:     'Fractal Tree',
    downloadLink: 'FractalTree.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 17,
    tags: ['Challenge', 'Visualization'],
    title: 'Fun Fractal Trees',
    shortDescription: 'Bug? No, <i>feature!</i>',
    imgpath: 'CodingChallenges/18.FunFractalTrees/image.png',
    filepath: 'CodingChallenges/18.FunFractalTrees/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=0jjeOYMjmDU',
    description: 'One of the bugs I ran into while making ',
    algLink:     'fractal trees.',
    downloadLink: 'FFT.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 18,
    tags: ['Challenge', 'Visualization'],
    title: 'OOP Fractal Trees',
    shortDescription: 'Object Oriented Fractal Trees',
    imgpath: 'CodingChallenges/19.OOPFractalTrees/image.png',
    filepath: 'CodingChallenges/19.OOPFractalTrees/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=fcdNSZ9IzJM',
    description: 'Fractal Trees created using ',
    algLink:     'OOP',
    downloadLink: 'OOPFT.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 19,
    tags: ['Challenge', 'Visualization'],
    title: 'L-System Example',
    shortDescription: 'Create a plant from sentences!',
    imgpath: 'CodingChallenges/20.L-System-Example/image.png',
    filepath: 'CodingChallenges/20.L-System-Example/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=E1B4UoSQMFw',
    description: 'This plant is made with a SENTENCE! <br> Open the <b>console</b> to see the process. <br> ',
    algLink:     'More Information',
    downloadLink: 'L-System-Example.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 20,
    tags: ['Challenge', 'Visualization'],
    title: 'L-System Fractal Plant',
    shortDescription: 'Fractal Tree? No, <i>Fractal Plant</i>',
    imgpath: 'CodingChallenges/21.L-System-Fractal-Plant/image.png',
    filepath: 'CodingChallenges/21.L-System-Fractal-Plant/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/L-system#Example_7:_Fractal_plant',
    description: 'This plant is made with a SENTENCE! <br> Open the <b>console</b> and <b>download</b> the code to see more. <br> ',
    algLink:     'More Information',
    downloadLink: 'L-System-Fractal-Plant.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 21,
    tags: ['Challenge', 'Visualization'],
    title: 'L-System Binary Tree',
    shortDescription: 'Create a Binary Tree using an L-System.',
    imgpath: 'CodingChallenges/22.L-System-Binary-Tree/image.png',
    filepath: 'CodingChallenges/22.L-System-Binary-Tree/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/L-system#Example_2:_Fractal_(binary)_tree',
    description: 'This tree is made with a SENTENCE! <br> Open the <b>console</b> and <b>download</b> the code to see more. <br> ',
    algLink:     'More Information',
    downloadLink: 'L-System-Binary-Tree.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 22,
    tags: ['Challenge', 'Visualization'],
    title: 'Space Colonization',
    shortDescription: 'Watch a tree grow to find its leaves.',
    imgpath: 'CodingChallenges/23.SpaceColonization/image.png',
    filepath: 'CodingChallenges/23.SpaceColonization/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=kKT0v3qhIQY',
    description: 'This tree will grow to find its leaves. <br><b>Click on the canvas</b> to add more leaves!<br><b>Download</b> the code to see more. <br> Or learn more ',
    algLink:     'here.',
    downloadLink: 'SpaceColonization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 23,
    tags: ['Challenge', 'Visualization'],
    title: 'Mendelbrot Set',
    shortDescription: 'Visualization of the famous Mendelbrot Set.',
    imgpath: 'CodingChallenges/24.MandelbrotSet/image.png',
    filepath: 'CodingChallenges/24.MandelbrotSet/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/Mandelbrot_set',
    description: 'Visualization of the famous ',
    algLink:     'Mendelbrot Set.',
    downloadLink: 'MendelbrotSet.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 24,
    tags: ['Challenge', 'Visualization'],
    title: 'Julia Sets',
    shortDescription: 'Comming Soon!',
    imgpath: 'CodingChallenges/25.JuliaSets/image.png',
    filepath: 'CodingChallenges/25.JuliaSets/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/Julia_set',
    description: 'A julia set is created by zooming in on a subsection of the Mendelbrot Set <br><b>Download</b> the code to see more. <br> Click ',
    algLink:     'here </a> to learn more',
    downloadLink: 'JuliaSets.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 24,
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Phyllotaxis',
    shortDescription: 'An example of algorithmix Botany!',
    imgpath: 'CodingChallenges/26.Phyllotaxis/image.png',
    filepath: 'CodingChallenges/26.Phyllotaxis/index.html',
    rosettaLink: 'http://algorithmicbotany.org/papers/abop/abop-ch4.pdf',
    description: 'An example of ',
    algLink:     'algorithmix Botany!',
    downloadLink: 'Phyllotaxis.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 25,
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Fireworks',
    shortDescription: 'Watch fireworks light up the sky.',
    imgpath: 'CodingChallenges/27.Fireworks/image.png',
    filepath: 'CodingChallenges/27.Fireworks/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=CKeyIbT3vXI',
    description: 'Watch ',
    algLink:     'fireworks</a> light up the sky!',
    downloadLink: 'fireworks.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 26,
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: '<i>Next Project</i>',
    shortDescription: 'Comming Soon!',
    imgpath: 'Resources/CommingSoon/image.jpg',
    // filepath: 'CodingChallenges/27.Fireworks/Code/index.html',
    filepath: '#',
    rosettaLink: '#',
    description: '#',
    algLink:     '#',
    downloadLink: '#',
    p5: true,
    console: false,
    visible: true
  }
]

var tags = [
  'All',
  'Sorting',
  'JavaScript',
  'Visualization',
  'Math',
  'Cryptography',
  'Console',
  'Challenge',
  'Game'
]
