var programs = [
  {
    number: 1,
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Bubble Sort',
    shortDescription: 'Visual representation of the Bubble sort algorithm.',
    imgpath: 'Sorting/1.%20Bubble%20Sort/image.png',
    filepath: 'Sorting/1.%20Bubble%20Sort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Bubble_sort',
    description: 'This is a visual representation of the ',
    algLink:     'Bubble sort algorithm',
    downloadLink: 'Bubble%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 2,
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Count Sort',
    shortDescription: 'Visual representation of the Count sort algorithm.',
    imgpath: 'Sorting/2.%20Count%20Sort/image.png',
    filepath: 'Sorting/2.%20Count%20Sort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Counting_sort',
    description: 'This is a visual representation of the ',
    algLink:     'Count sort algorithm',
    downloadLink: 'Count%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 3,
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Gnome Sort',
    shortDescription: 'Visual representation of the Gnome sort algorithm.',
    imgpath: 'Sorting/3.%20Gnome%20Sort/image.png',
    filepath: 'Sorting/3.%20Gnome%20Sort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Gnome_sort',
    description: 'This is a visual representation of the ',
    algLink:     'Gnome sort algorithm',
    downloadLink: 'Gnome%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 4,
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Insertion Sort',
    shortDescription: 'Visual representation of the Insertion sort algorithm.',
    imgpath: 'Sorting/4.%20Insertion%20Sort/image.png',
    filepath: 'Sorting/4.%20Insertion%20Sort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Insertion_sort',
    description: 'This is a visual representation of the ',
    algLink:     'Insertion sort algorithm',
    downloadLink: 'Insertion%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 5,
    tags: ['Math', 'JavaScript', 'Visualization'],
    title: 'Babbage Problem',
    shortDescription: 'Solving the Charles Babbage problem',
    imgpath: 'Projects/6.Babbage-Problem/image.png',
    filepath: 'Projects/6.Babbage-Problem/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Babbage_problem',
    description: 'This program solves the ',
    algLink:     'Babbage Problem',
    downloadLink: 'Babbage-Problem.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 6,
    tags: ['Math', 'JavaScript', 'Visualization'],
    title: 'Binary Numbers',
    shortDescription: 'Converting Base 10 to 2',
    imgpath: 'Projects/7.BinaryNumbers/image.png',
    filepath: 'Projects/7.BinaryNumbers/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Binary_digits',
    description: 'Converts base 10 numbers to ',
    algLink:     'binary digits.',
    downloadLink: 'BinaryNumbers.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 7,
    tags: ['Cryptography', 'JavaScript', 'Console'],
    title: 'Caesar Cipher',
    shortDescription: 'Encrypt/Decrypt text using a Caesar Cipher',
    imgpath: 'Projects/8.Caesar-Cipher/image.png',
    filepath: 'Projects/8.Caesar-Cipher/index.html',
    rosettaLink: 'https://www.rosettacode.org/wiki/Caesar_cipher',
    description: 'Encrypt/Decrypt text using a ',
    algLink:     'Caesar Cipher.',
    downloadLink: 'Caesar-Cipher.zip',
    p5: false,
    console: true,
    visible: true
  },
  {
    number: 8,
    tags: ['Cryptography', 'JavaScript', 'Console'],
    title: 'Rot-13 Cipher',
    shortDescription: 'Encrypt/Decrypt text using a Rot-13 Cipher',
    imgpath: 'Projects/9.Rot-13/image.png',
    filepath: 'Projects/9.Rot-13/index.html',
    rosettaLink: 'https://www.rosettacode.org/wiki/Rot-13',
    description: 'Encrypt/Decrypt text using a ',
    algLink:     'Rot-13 Cipher.',
    downloadLink: 'Rot-13.zip',
    p5: false,
    console: true,
    visible: true
  },
  {
    number: 9,
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Starfield',
    shortDescription: 'Fly through space at warpspeed!',
    imgpath: 'CodingChallenges/10.Starfield/image.png',
    filepath: 'CodingChallenges/10.Starfield/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=17WoOqgXsRM',
    description: 'Fly through space at ',
    algLink:     'warpspeed!',
    downloadLink: 'Starfield.zip',
    p5: true,
    console: false,
    visible: true
  },
  {
    number: 10,
    tags: ['Challenge', 'JavaScript', 'Game'],
    title: 'Snake Game',
    shortDescription: 'Play the retro arcade game: Snake',
    imgpath: 'CodingChallenges/11.SnakeGame/image.png',
    filepath: 'CodingChallenges/11.SnakeGame/index.html',
    rosettaLink: 'https://youtu.be/AaGK-fj-BAM',
    description: 'Use the <b>Arrow Keys</b> to play the ',
    algLink:     'Snake Game!',
    downloadLink: 'SnakeGame.zip',
    p5: true,
    console: false,
    visible: true
  }
]

var tags = [
  'All',
  'Sorting',
  'JavaScript',
  'Visualization',
  'Math',
  'Cryptography',
  'Console',
  'Challenge',
  'Game'
]
