var programs = [{
    number: 0,
    keyWords: ['development'],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: '<i>Next Project</i>',
    shortDescription: 'Comming Soon!',
    imgpath: 'Projects/0.Dev/image.jpg',
    filepath: 'Projects/0.Dev/Code/index.html',
    rosettaLink: '#',
    description: '#',
    algLink: '#',
    downloadLink: '#',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 1,
    keyWords: ['sorting', 'javascript', 'visualization', 'p5.js', 'algorithm', 'bubble sort', 'rosetta code', 'coding challenge'],
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Bubble Sort',
    shortDescription: 'Visual representation of the Bubble sort algorithm.',
    imgpath: 'Projects/1.BubbleSort/image.png',
    filepath: 'Projects/1.BubbleSort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Bubble_sort',
    description: 'This is a visual representation of the ',
    algLink: 'Bubble sort algorithm',
    downloadLink: 'Bubble%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 2,
    keyWords: ['sorting', 'javascript', 'visualization', 'p5.js', 'algorithm', 'count sort', 'rosetta code'],
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Count Sort',
    shortDescription: 'Visual representation of the Count sort algorithm.',
    imgpath: 'Projects/2.CountSort/image.png',
    filepath: 'Projects/2.CountSort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Counting_sort',
    description: 'This is a visual representation of the ',
    algLink: 'Count sort algorithm',
    downloadLink: 'Count%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 3,
    keyWords: ['sorting', 'javascript', 'visualization', 'p5.js', 'algorithm', 'gnome sort', 'rosetta code'],
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Gnome Sort',
    shortDescription: 'Visual representation of the Gnome sort algorithm.',
    imgpath: 'Projects/3.GnomeSort/image.png',
    filepath: 'Projects/3.GnomeSort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Gnome_sort',
    description: 'This is a visual representation of the ',
    algLink: 'Gnome sort algorithm',
    downloadLink: 'Gnome%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 4,
    keyWords: ['sorting', 'javascript', 'visualization', 'p5.js', 'algorithm', 'insertion sort', 'rosetta code'],
    tags: ['Sorting', 'JavaScript', 'Visualization'],
    title: 'Insertion Sort',
    shortDescription: 'Visual representation of the Insertion sort algorithm.',
    imgpath: 'Projects/4.InsertionSort/image.png',
    filepath: 'Projects/4.InsertionSort/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Sorting_algorithms/Insertion_sort',
    description: 'This is a visual representation of the ',
    algLink: 'Insertion sort algorithm',
    downloadLink: 'Insertion%20Sort%20Visualization.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 5,
    keyWords: ['javascript', 'visualization', 'math', 'rosetta code', 'babbage problem'],
    tags: ['Math', 'JavaScript', 'Visualization'],
    title: 'Babbage Problem',
    shortDescription: 'Solving the Charles Babbage problem',
    imgpath: 'Projects/5.BabbageProblem/image.png',
    filepath: 'Projects/5.BabbageProblem/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Babbage_problem',
    description: 'This program solves the ',
    algLink: 'Babbage Problem',
    downloadLink: 'Babbage-Problem.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 6,
    keyWords: ['javascript', 'visualization', 'math', 'rosetta code', 'binary numbers'],
    tags: ['Math', 'JavaScript', 'Visualization'],
    title: 'Binary Numbers',
    shortDescription: 'Converting Base 10 to 2',
    imgpath: 'Projects/6.BinaryNumbers/image.png',
    filepath: 'Projects/6.BinaryNumbers/index.html',
    rosettaLink: 'http://www.rosettacode.org/wiki/Binary_digits',
    description: 'Converts base 10 numbers to ',
    algLink: 'binary digits.',
    downloadLink: 'BinaryNumbers.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 7,
    keyWords: ['javascript', 'cryptography', 'console', 'rosetta code', 'caesar cipher'],
    tags: ['Cryptography', 'JavaScript', 'Console'],
    title: 'Caesar Cipher',
    shortDescription: 'Encrypt/Decrypt text using a Caesar Cipher',
    imgpath: 'Projects/7.CaesarCipher/image.png',
    filepath: 'Projects/7.CaesarCipher/index.html',
    rosettaLink: 'https://www.rosettacode.org/wiki/Caesar_cipher',
    description: 'Encrypt/Decrypt text using a ',
    algLink: 'Caesar Cipher.',
    downloadLink: 'Caesar-Cipher.zip',
    p5: false,
    console: true,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 8,
    keyWords: ['javascript', 'cryptography', 'console', 'rosetta code', 'rot-13 cipher'],
    tags: ['Cryptography', 'JavaScript', 'Console'],
    title: 'Rot-13 Cipher',
    shortDescription: 'Encrypt/Decrypt text using a Rot-13 Cipher',
    imgpath: 'Projects/8.Rot13/image.png',
    filepath: 'Projects/8.Rot13/index.html',
    rosettaLink: 'https://www.rosettacode.org/wiki/Rot-13',
    description: 'Encrypt/Decrypt text using a ',
    algLink: 'Rot-13 Cipher.',
    downloadLink: 'Rot-13.zip',
    p5: false,
    console: true,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 9,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'starfield', 'space'],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Starfield',
    shortDescription: 'Fly through space at warpspeed!',
    imgpath: 'Projects/9.Starfield/image.png',
    filepath: 'Projects/9.Starfield/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=17WoOqgXsRM',
    description: 'Fly through space at ',
    algLink: 'warpspeed!',
    downloadLink: 'Starfield.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 10,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'snake', 'game', 'retro', 'arcade', 'simple'],
    tags: ['Challenge', 'JavaScript', 'Game'],
    title: 'Snake',
    shortDescription: 'Play the retro arcade game: Snake',
    imgpath: 'Projects/10.SnakeGame/image.png',
    filepath: 'Projects/10.SnakeGame/index.html',
    rosettaLink: 'https://youtu.be/AaGK-fj-BAM',
    description: 'Use the <b>Arrow Keys</b> to play the ',
    algLink: 'Snake Game!',
    downloadLink: 'SnakeGame.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 11,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'purple rain', 'beautiful', 'calming'],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Purple Rain',
    shortDescription: 'Play in the Purple Rain!',
    imgpath: 'Projects/11.PurpleRain/image.png',
    filepath: 'Projects/11.PurpleRain/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=KkyIDI6rQJI',
    description: 'Watch the ',
    algLink: 'Purple Rain fall!',
    downloadLink: 'PurpleRain.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 12,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'game', 'space invaders', 'retro', 'arcade', 'simple'],
    tags: ['Challenge', 'JavaScript', 'Game'],
    title: 'Space Invaders',
    shortDescription: 'Play the classic: Space Invaders',
    imgpath: 'Projects/12.SpaceInvaders/image.png',
    filepath: 'Projects/12.SpaceInvaders/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=biN3v3ef-Y0',
    description: 'Use <b>"A"</b> and <b>"D"</b> to move and <b>Spacebar</b> to shoot - ',
    algLink: 'Space Invaders',
    downloadLink: 'SpaceInvaders.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 13,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'solar system'],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Solar System',
    shortDescription: 'Solar System Simulation!',
    imgpath: 'Projects/13.SolarSystem/image.png',
    filepath: 'Projects/13.SolarSystem/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=l8SiJ-RmeHU',
    description: 'A Solar System ',
    algLink: 'Simulation!',
    downloadLink: 'SolarSystem.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 14,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'maze generator',
      'algorithm', 'fun', 'recursive', 'recursion'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'Maze Generator',
    shortDescription: 'Generate a maze using a recursive backtracker!',
    imgpath: 'Projects/14.MazeGenerator/image.png',
    filepath: 'Projects/14.MazeGenerator/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/Maze_generation_algorithm#Recursive_backtracker',
    description: 'Generates a maze using a ',
    algLink: 'Recursive backtracker',
    downloadLink: 'MazeGenerator.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 15,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'algorithm', 'rda'],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'RDA!',
    shortDescription: 'Reaction Diffusion Algorithm Simulation',
    imgpath: 'Projects/15.ReactionDiffusion/image.png',
    filepath: 'Projects/15.ReactionDiffusion/index.html',
    rosettaLink: 'http://karlsims.com/rd.html',
    description: 'This is a Simulation based on the ',
    algLink: 'Reaction Diffusion Algorithm',
    downloadLink: 'ReactionDiffusionAlg.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 16,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'fractal tree',
      'algorithm', 'fun', 'recursive', 'recursion', 'beautiful', 'featured', 'colorful', 'trees'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'Fractal Tree - Recursive',
    shortDescription: 'Build a fractal tree recursively.',
    imgpath: 'Projects/16.FractalTrees/image.png',
    filepath: 'Projects/16.FractalTrees/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=0jjeOYMjmDU',
    description: 'Animated Recursive',
    algLink: 'Fractal Tree',
    downloadLink: 'FractalTree.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 17,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'fractal tree',
      'algorithm', 'fun', 'recursive', 'recursion', 'beautiful', 'bug', 'fun fractal trees', 'trees'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'Fun Fractal Trees',
    shortDescription: 'Bug? No, <i>feature!</i>',
    imgpath: 'Projects/17.FunFractalTrees/image.png',
    filepath: 'Projects/17.FunFractalTrees/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=0jjeOYMjmDU',
    description: 'One of the bugs I ran into while making ',
    algLink: 'fractal trees.',
    downloadLink: 'FFT.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 18,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train', 'fractal tree',
      'algorithm', 'fun', 'recursive', 'recursion', 'beautiful', 'bug', 'oop fractal trees', 'trees'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'OOP Fractal Trees',
    shortDescription: 'Object Oriented Fractal Trees',
    imgpath: 'Projects/18.OOPFractalTrees/image.png',
    filepath: 'Projects/18.OOPFractalTrees/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=fcdNSZ9IzJM',
    description: 'Fractal Trees created using ',
    algLink: 'OOP',
    downloadLink: 'OOPFT.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 19,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'l-system', 'l system', 'example', 'l-system example', 'plant', 'trees', 'sentence'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'L-System Example',
    shortDescription: 'Create a plant from sentences!',
    imgpath: 'Projects/19.L-System-Example/image.png',
    filepath: 'Projects/19.L-System-Example/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=E1B4UoSQMFw',
    description: 'This plant is made with a SENTENCE! <br> Open the <b>console</b> to see the process. <br> ',
    algLink: 'More Information',
    downloadLink: 'L-System-Example.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 20,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'l-system', 'l system', 'fractal plant', 'l-system fractal plant', 'plant', 'trees', 'sentence', 'featured'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'L-System Fractal Plant',
    shortDescription: 'Fractal Tree? No, <i>Fractal Plant</i>',
    imgpath: 'Projects/20.L-System-Fractal-Plant/image.png',
    filepath: 'Projects/20.L-System-Fractal-Plant/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/L-system#Example_7:_Fractal_plant',
    description: 'This plant is made with a SENTENCE! <br> Open the <b>console</b> and <b>download</b> the code to see more. <br> ',
    algLink: 'More Information',
    downloadLink: 'L-System-Fractal-Plant.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 21,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'l-system', 'l system', 'l-system binary tree', 'plant', 'trees', 'sentence'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'L-System Binary Tree',
    shortDescription: 'Create a Binary Tree using an L-System.',
    imgpath: 'Projects/21.L-System-Binary-Tree/image.png',
    filepath: 'Projects/21.L-System-Binary-Tree/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/L-system#Example_2:_Fractal_(binary)_tree',
    description: 'This tree is made with a SENTENCE! <br> Open the <b>console</b> and <b>download</b> the code to see more. <br> ',
    algLink: 'More Information',
    downloadLink: 'L-System-Binary-Tree.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 22,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'plant', 'trees', 'interactive', 'vectors', 'space colonization'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'Space Colonization',
    shortDescription: 'Watch a tree grow to find its leaves.',
    imgpath: 'Projects/22.SpaceColonization/image.png',
    filepath: 'Projects/22.SpaceColonization/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=kKT0v3qhIQY',
    description: 'This tree will grow to find its leaves. <br><b>Click on the canvas</b> to add more leaves!<br><b>Download</b> the code to see more. <br> Or learn more ',
    algLink: 'here.',
    downloadLink: 'SpaceColonization.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 23,
    tags: ['Challenge', 'Visualization'],
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'math', 'cool', 'imaginary', 'numbers', 'mendelbrot set', 'julia set', 'sets'
    ],
    title: 'Mendelbrot Set',
    shortDescription: 'Visualization of the famous Mendelbrot Set.',
    imgpath: 'Projects/23.MandelbrotSet/image.png',
    filepath: 'Projects/23.MandelbrotSet/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/Mandelbrot_set',
    description: 'Visualization of the famous ',
    algLink: 'Mendelbrot Set.',
    downloadLink: 'MendelbrotSet.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 24,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'math', 'cool', 'imaginary', 'numbers', 'mendelbrot set', 'julia set', 'sets'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'Julia Sets',
    shortDescription: 'Subsections of the Mendelbrot set.',
    imgpath: 'Projects/24.JuliaSets/image.png',
    filepath: 'Projects/24.JuliaSets/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/Julia_set',
    description: 'A julia set is created by zooming in on a subsection of the Mendelbrot Set <br><b>Download</b> the code to see more. <br> Click ',
    algLink: 'here </a> to learn more',
    downloadLink: 'JuliaSets.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 25,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'math', 'cool', 'phyllotaxis', 'algorithmic', 'botany', 'algorithmic botany', 'plant', 'colorful',
      'beautiful', 'real world'
    ],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Phyllotaxis',
    shortDescription: 'An example of algorithmic Botany!',
    imgpath: 'Projects/25.Phyllotaxis/image.png',
    filepath: 'Projects/25.Phyllotaxis/index.html',
    rosettaLink: 'http://algorithmicbotany.org/papers/abop/abop-ch4.pdf',
    description: 'An example of ',
    algLink: 'algorithmix Botany!',
    downloadLink: 'Phyllotaxis.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 26,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'cool', 'fireworks', 'colorful', 'beautiful', 'particals', 'vectors', 'physics'
    ],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Fireworks',
    shortDescription: 'Watch fireworks light up the sky.',
    imgpath: 'Projects/26.Fireworks/image.png',
    filepath: 'Projects/26.Fireworks/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=CKeyIbT3vXI',
    description: 'Watch ',
    algLink: 'fireworks</a> light up the sky!',
    downloadLink: 'fireworks.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 27,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'cool', 'rockets', 'colorful', 'smart', 'particals', 'vectors', 'physics', 'smart rockets',
      'evolution', 'nature of code', 'dna', 'featured'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'Smart Rockets',
    shortDescription: 'Watch rockets evolve to hit a target.',
    imgpath: 'Projects/27.SmartRockets/image.png',
    filepath: 'Projects/27.SmartRockets/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=bGz7mv2vD6g',
    description: 'Watch these rockets ',
    algLink: 'evolve </a> to hit a target. <br> Usually around generation 15-20 :)',
    downloadLink: 'SmartRockets.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 28,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'algorithm', 'tsm', 'traveling salesman', 'famous'
    ],
    tags: ['Challenge', 'Visualization'],
    title: 'Traveling Salesman',
    shortDescription: 'The famous traveling salesman problem.',
    imgpath: 'Projects/28.TSMP/image.png',
    filepath: 'Projects/28.TSMP/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=BAejnwN4Ccw',
    description: 'A visualization of the ',
    algLink: ' traveling salesman problem',
    downloadLink: 'TSMP.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 29,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'cool', 'sorting', 'pixel sorting', 'fun', 'm&ms'
    ],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Pixel Sorting!',
    shortDescription: 'Watch an image get sorted by brightness.',
    imgpath: 'Projects/29.PixelSorting/image.png',
    filepath: 'Projects/29.PixelSorting/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=JUDYkxU6J0o',
    description: 'Each pixel is being sorted by brightness.<br> Mre about that ',
    algLink: 'here.',
    downloadLink: 'PixelSorting.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 30,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'cool', 'beautiful', 'colorful', 'circle packing', 'fun', 'physics', 'vectors', 'featured'
    ],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Circle Packing',
    shortDescription: 'Circle Packing with simple physics.',
    imgpath: 'Projects/30.CirclePacking/image.png',
    filepath: 'Projects/30.CirclePacking/index.html',
    rosettaLink: 'https://www.youtube.com/watch?v=QHEQuoIKgNE',
    description: 'This combines ',
    algLink: 'circle packing</a> and steering. <br> Move your mouse around the screen.',
    downloadLink: 'CirclePacking.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 31,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'cool', 'beautiful', 'colorful', 'noise trees', 'fun', 'perlin noise', 'perlin', 'trees', 'fractal',
      'wind', 'fractal trees'
    ],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'Noise Trees',
    shortDescription: 'Fractal Trees blown by perlin noise.',
    imgpath: 'Projects/31.NoiseTrees/image.png',
    filepath: 'Projects/31.NoiseTrees/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/Perlin_noise',
    description: 'Fractal Trees blown by ',
    algLink: 'perlin noise.',
    downloadLink: 'NoiseTrees.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 32,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'cool', 'maze', 'path finding', 'a*', 'game', 'animation', 'search algorithm', 'algorithm', 'featured'
    ],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'A*',
    shortDescription: 'Comming Soon!',
    imgpath: 'Projects/32.AStar/image.png',
    filepath: 'Projects/32.AStar/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/A*_search_algorithm',
    description: 'Watch the ',
    algLink: 'A*</a> algorithm work through a field of obstacles.',
    downloadLink: 'AStar.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  },
  {
    number: 33,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
      'cool', 'maze', 'path finding', 'a*', 'game', 'animation', 'search algorithm', 'algorithm',
      'maze generation', 'combination', 'a* maze', 'featured'
    ],
    tags: ['Challenge', 'JavaScript', 'Visualization'],
    title: 'A* Maze!',
    shortDescription: 'This is super cool and you need to watch.',
    imgpath: 'Projects/33.AStarMaze/image.png',
    filepath: 'Projects/33.AStarMaze/index.html',
    rosettaLink: 'https://en.wikipedia.org/wiki/A*_search_algorithm',
    description: 'Combines the Maze Generator with the ',
    algLink: 'A*</a> algorithm.',
    downloadLink: 'AStarMaze.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: '#e5e5e5'
  },
  {
    number: 34,
    keyWords: ['javascript', 'p5.js', 'visualization', 'challenge', 'shiffman', 'coding train',
               'physics', 'particle', 'example partical system', 'vectors'
    ],
    tags: ['Challenge'],
    title: 'Example Partical System',
    shortDescription: 'Simple physics engine.',
    imgpath: 'Projects/34.ParticalExample/image.png',
    filepath: 'Projects/34.ParticalExample/index.html',
    rosettaLink: 'https://natureofcode.com/book/chapter-4-particle-systems',
    description: 'A simple system of floating ',
    algLink: 'particals.',
    downloadLink: 'ParticalExample.zip',
    p5: true,
    console: false,
    visible: true,
    titleText: "#e5e5e5"
  }
]

var tags = [
  'Featured',
  'Beautiful',
  'Trees',
  'Vectors'
]

var Spotlight = 30;
